### ISSUE TITLE
Cessspool - Unable to land first day

### ISSUE THREAD

**Issue by Seviper** [Spookybuddy/LethalLoaderMods#5]
Howdy! Encountered an issue with the moon Cesspool and thought I'd share how to recreate the issue so it can hopefully be fixed.

1. Clean profile with only Cesspool + dependencies
2. Attempt to land at cesspool on day 1 of quota
3. Game crashes when pulling the lever to start landing

However, if you land on Cesspool on day 2, the moon functions as normal with no crashes. I'll include a log of the above method in case it gleans any helpful info, along with landing there on day 2. 

[LogOutput - Crash.log](https://github.com/Spookybuddy/LethalLoaderMods/files/15476314/LogOutput.log)

[LogOutput - No Crash.log](https://github.com/Spookybuddy/LethalLoaderMods/files/15476330/LogOutput.log)

**Comment by Spookybuddy** [comment]
I could not recreate your issue. Is this issue consistent for you?

**Comment by Seviper** [comment]
Yes, was able to recreate it just now.

**Comment by Nexxod** [comment]
I have the same issue as well even on a minimal mod setup (only General Improvements and ViewExtension), but it doesn't crash 100% of time, it is somewhat random and can happen on any day, not only the first one. I have attached the log where I was able to both load and crash on the first day on a fresh save each time.
The concept is pretty cool so I hope it is possible to find the culprit, but we had to disable the mod for now.
[LogOutput.log](https://github.com/user-attachments/files/15525104/LogOutput.log)

**Comment by ProjectBots** [comment]
+1

**Comment by Nexxod** [comment]
Just in case, if you're using Unity Terrain object check if "Draw Instanced" is checkmarked in its options. When it is disabled random crashes may occur due to worse performance, especially on complicated or large terrain.

**Comment by Spookybuddy** [comment]
The issue should be resolved now. The new version are available on the Thunderstore page. Please let me know if the crashes still occur.

**Comment by Seviper** [comment]
This worked out the first day issue for me! I hope it fixed other people's crashes as well. Thank you for your time.
