### ISSUE TITLE
Error about Dropship

### ISSUE THREAD

**Issue by Aaronek10** [Spookybuddy/LethalLoaderMods#8]
Console is spammed with error about Dropship reference.

**Comment by Spookybuddy** [comment]
A v60/v64 version will be made when I have the spare time. I will notify you when they are released.

**Comment by Aaronek10** [comment]
Thanks, this error causes huge problems sometimes with performance as well

**Comment by Aaronek10** [comment]
Ah, also another issue is that light system is broken, that means interiors have lights passing through walls or entire floor is weirdly highlighted removing whole darkness from interiors (Vanilla and modded)

**Comment by Spookybuddy** [comment]
The v64 updated moons should now be available on their Thunderstore pages. Thanks for reporting your issues, hopefully they are all resolved. Please make another report if you happen to run into any other problems.
